source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

abstract_target 'NPOKitAbstract' do
    pod 'CocoaLumberjack/Swift'

    target 'NPOKit' do
        platform :tvos, '10.0'

        pod 'Alamofire', '~> 4.0'
        pod 'AlamofireObjectMapper', '~> 4.0'
        pod 'AlamofireImage', '~> 3.0'
        pod 'RealmSwift'
    end
end
