source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

abstract_target 'NPOKitAbstract' do
    pod 'CocoaLumberjack/Swift'

    target 'NPOKit' do
        platform :tvos, '9.0'

        pod 'Alamofire', '~> 3.4'
        pod 'AlamofireObjectMapper', '~> 3.0'
        pod 'AlamofireImage', '~> 2.0'
        pod 'RealmSwift'
    end

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '2.2'
            end
        end
    end
end
