source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

abstract_target 'NPOKitAbstract' do
    pod 'CocoaLumberjack/Swift'

    target 'NPOKit' do
        platform :tvos, '10.0'

        pod 'Alamofire', '~> 4.0'
        pod 'AlamofireObjectMapper', '~> 4.0'
        pod 'AlamofireImage', '~> 3.1'
        pod 'RealmSwift'
        pod 'XCDYouTubeKit', '~> 2.5'
        pod 'GoogleAPIClientForREST/YouTube'
    end
end
