disabled_rules:
  - line_length
  - trailing_whitespace
  - todo
  - large_tuple
  - notification_center_detachment
opt_in_rules:
  - force_unwrapping
excluded:
  - Carthage
  - Pods
  - NPOKit/Pods
variable_name:
    min_length: 2
file_length:
    warning: 600
    error: 1200
type_body_length:
    warning: 350
    error: 500
