language: objective-c
os: osx
osx_image: xcode8.1
env:
    global:
    - NSUnbufferedIO=YES
install: ./bin/install_swiftlint.sh
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcodebuild -list
    - xcodebuild -workspace "UitzendingGemist.xcworkspace" -list
    - xcpretty -v
    - swiftlint
    - xcodebuild -workspace "UitzendingGemist.xcworkspace" -scheme "UitzendingGemist" -sdk "appletvsimulator10.0" -destination "platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p" -configuration Release clean build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO RUN_CLANG_STATIC_ANALYZER=YES|xcpretty -c
