language: objective-c
os: osx
osx_image: xcode8
install: ./bin/install_swiftlint.sh
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - swiftlint
    - xcodebuild -workspace UitzendingGemist.xcworkspace -scheme UitzendingGemist -sdk appletvsimulator10.0 -destination "OS=10.0,name=Apple TV 1080p" -configuration Debug clean build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO|xcpretty -c
